# Generated by Django 2.0.2 on 2018-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniReg', '0003_aniregform'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniregform',
            name='comments',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='aniregform',
            name='animale_type',
            field=models.CharField(choices=[('CHICKEN', 'Chicken'), ('FOWL', 'Fowl'), ('DUCK', 'Duck'), ('TURKEY', 'Turkey'), ('OTHER', 'Other bird')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aniregform',
            name='disease_type',
            field=models.CharField(choices=[('NC', 'Newcastle Disease'), ('FP', 'Fowl Pox'), ('IBD', 'Infectious Bursal Disease'), ('MD', 'Mareks Disease'), ('OD', 'Other Disease')], max_length=1),
        ),
    ]
