# Generated by Django 2.0.2 on 2018-04-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniReg', '0004_auto_20180423_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniregform',
            name='comments',
            field=models.TextField(default=' '),
        ),
    ]
