# Generated by Django 2.0.2 on 2018-04-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniReg', '0005_auto_20180423_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniregform',
            name='animale_type',
            field=models.CharField(choices=[('CKN', 'Chicken'), ('FWL', 'Fowl'), ('DCK', 'Duck'), ('TKY', 'Turkey'), ('OTH', 'Other bird')], max_length=3),
        ),
        migrations.AlterField(
            model_name='aniregform',
            name='disease_type',
            field=models.CharField(choices=[('NC', 'Newcastle Disease'), ('FP', 'Fowl Pox'), ('IB', 'Infectious Bursal Disease'), ('MD', 'Mareks Disease'), ('OD', 'Other Disease')], max_length=2),
        ),
    ]
