# Generated by Django 2.0.2 on 2018-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniReg', '0006_auto_20180423_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniregform',
            name='treatment_1',
            field=models.TextField(default=' '),
        ),
    ]
